### PR TITLE
Handle sprocket 3 manifest filename

### PR DESCRIPTION
**Pull request by chulkilee**
See https://github.com/rails/sprockets/commit/ce6508e8540f829c6221afa39fdf718e4dded096

### CODE REVIEW

**Comment by i5okie** [comment]
did ```gem 'capistrano-rails', :git => 'https://github.com/chulkilee/capistrano-rails.git', :branch => 'sprocket-3'``` in gemfile

bundle update,,  cap bundler:install, production deploy..
still getting the error.

**Comment by chulkilee** [comment]
Please copy and paste your error message. I know it's https://github.com/capistrano/rails/pull/112#issuecomment-93859434 but nobody can know that from your comment.

Make sure you run cap in bundler - `bundle exec cap production deploy`.

**Comment by Tietew** [comment]
Looks good. `deploy` works for me.
`deploy:rollback` still fails in same reason as https://github.com/capistrano/rails/pull/112#discussion-diff-28394896 ...

**Comment by kirs** [comment]
Thanks!

**Pull request merged**
