### PR TITLE
Ensure assets backup path is in place

### PR DESCRIPTION
**Pull request by mrreynolds**
This fixes an otherwise failing capistrano task. Related to #33.

### CODE REVIEW

**Comment by goivemaster** [comment]
Just used this to fix the same issue for me, thanks

**Comment by mrreynolds** [comment]
@kirs @leehambley any chance for this to get merged?

**Comment by leehambley** [comment]
I try not to touch this gem, @kirs ?

**Comment by kirs** [comment]
Thanks @mrreynolds!

**Pull request merged**
