### PR TITLE
Run any rake task on remote

### PR DESCRIPTION
**Pull request by stoivo**
Our company uses rake task to migrate data. 
It would be nice If capistrano-rails provided this. I check out the code and this is the smallest amount of code I could add to make it work simply. I know I could package it up and ship it as a separate gem out of I don't see how anybody would benefit from that. 

Probably I should not use migration_servers always, but make it configurable?
Are you interested in adding this?

### CODE REVIEW

**Comment by stoivo** [comment]
This would also solve #110 (rake db:rollback)

**Comment by stoivo** [comment]
@kirs @mattbrictson

**Comment by will-in-wi** [comment]
IMHO, building a generic system for running arbitrary rake tasks from the command line is beyond the scope of core capistrano/rails. The degree of configurability required in the long run is likely to be an issue (around picking servers, etc). The Capistrano configuration syntax is essentially already designed to do this, and if you really need arbitrary rake tasks to be run, you can add the code block in the PR.

This might be another good candidate for my "Cookbook" doc page idea… https://github.com/capistrano/rails/issues/199#issuecomment-333403472

I'm entirely open to different opinions from the other Cap maintainers.

**Comment by stoivo** [comment]
I to some degree agree, in our case, we have moved the code to populate new fields into rake task. These are some tasks that will only be run once. I would just add a file for our case and would probably good enough for us. I just thought that this was a common case.

Thanks for the comment 🎉

**Comment by stoivo** [comment]
Cookbook idea might not be a bad idea

**Comment by will-in-wi** [comment]
The cookbook has been merged. Closing this pull request.

**Comment by stoivo** [comment]
Ok, cool cook book

**Pull request closed without merging**
