### PR TITLE
Updates migrations.rake

### PR DESCRIPTION
**Pull request by chilian**
Checks also changes in subfolders of the "release_path/db/migrate" - folder

### CODE REVIEW

**Comment by kirs** [comment]
What's the usecase?
From my experience with Rails, `db/migrations` is always flat.

**Comment by chilian** [comment]
Usecase: Some bigger projects with many migrations which are stored in subfolders e.g. for each version (e.g. `db/migrations/v1.0/create_user.rb`, `db/migrations/v1.1/create_user_addresses.rb`)

**Comment by BM5k** [comment]
@chilian I think this may also be solved by #183

**Comment by mattbrictson** [comment]
This PR has the right idea, but I think even better would be to compare the whole `db` directory instead of just `db/migrate`. It looks like the OP has abandoned this PR, so I am closing it as part of cleaning up old PRs.

**Pull request closed without merging**
