### PR TITLE
Add support for multiple migration servers

### PR DESCRIPTION
**Pull request by AmirKremer**

### CODE REVIEW

**Comment by ledermann** [comment]
+1

**Comment by numbata** [comment]
+1

**Comment by PanfilovDenis** [comment]
+1 merge and close this PR!

**Comment by mattbrictson** [comment]
Hello! I'm considering merging this PR, but I'd like to see a slightly different configuration system that is more consistent with what we already have in the `capistrano-bundler` gem.

@AmirKremer what do you think of configuration like this:

```ruby
# These are the defaults
set :migration_role, :db
set :migration_servers, -> { primary(fetch(:migration_role)) }
```

This would keep the default behavior unchanged, but allow the server criteria to be changed with any arbitrary Proc. For example, to support multiple migration servers:

```ruby
set :migration_servers, -> { fetch(:migration_role) }
```

This would be consistent with the `bundle_roles` and `bundle_servers` settings we have in the `capistrano-bundler` gem. (See that project's [README](https://github.com/capistrano/bundler#usage).)

**Comment by will-in-wi** [comment]
I think this was fixed in https://github.com/capistrano/rails/pull/168

**Comment by mattbrictson** [comment]
@will-in-wi Good catch, thanks!

**Pull request closed without merging**
